app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    password_secure = db.Column(db.String(255))
    comment = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    pitch = db.relationship('Pitch',backref = 'user',lazy = "dynamic")
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.password_hash, password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'
class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitches'
    id =db.Column(db.Integer,primary_key=True)
    pitch_content =db.Column(db.String())
    pitch_category =db.Column(db.String(255))
    user_id= db.Column(db.Integer,db.ForeignKey('users.id'))


    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,id):
        pitches = Pitch.query.filter_by(id=id).all()
        return pitches
    @classmethod
    def get_all_pitches(cls):
        pitches =Pitch.query.order_by('-id').all()
        return pitches
    @classmethod
    def get_category(cls,cat):
        category =Pitch.query.filter_by(pitch_category=cat).order_by('-id').all()
        return category

class Comment(db.Model):
   __tablename__ = 'comments'

   id = db.Column(db.Integer, primary_key=True)
   comment_content = db.Column(db.String())
   pitch_id = db.Column(db.Integer)
   user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

   def save_comment(self):
       db.session.add(self)
       db.session.commit()

   @classmethod
   def get_comments(cls, id):
       comments = Comment.query.filter_by(pitch_id=id).all()
       return comments



class PhotoProfile(db.Model):
   __tablename__ = 'profile_photos'

   id = db.Column(db.Integer, primary_key=True)
   pic_path = db.Column(db.String())
   user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import Required

class CommentForm(FlaskForm):
 comment = TextAreaField('Comment title')

 submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class AddPitch(FlaskForm):
    pitch = TextAreaField('Write your pitch',validators =[Required()])
    category = RadioField('Pick Category',
                            choices=[('interview', 'interview'),
                                  ('product', 'product'),
                                     ('pick-up-lines', 'pick-up-lines')],
                            validators=[Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
   category = StringField('Pitch category',validators=[Required()])
   content = TextAreaField('Pitch', validators=[Required()])

   submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()
def create_app(config_name):
    app = Flask(__name__)


    # configure UploadSet
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)
    # Registering the blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask_login import login_required, current_user
from flask import render_template,request,redirect,url_for,abort
from ..models import  User,Pitch,Comment
from .forms import CommentForm,UpdateProfile,AddPitch
from .. import db,photos
from . import main
import markdown2


@main.route('/')
def index():
    return render_template('index.html',title='tasha')

@main.route('/pitched/comment/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):
    form = CommentForm()
    pitch = Pitch.get_pitch(id)
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(pitch_id=id, comment_content=comment, user_id=current_user.id)
        new_comment.save_comment()
    comment = Comment.get_comments(id)

    return render_template('new_comment.html', comment_form=form, pitch=pitch, comment=comment)

@main.route('/pitched', methods=['GET', 'POST'])
def post():
    form = AddPitch()
    if form.validate_on_submit():
        new_pitch = Pitch(pitch_content=form.pitch.data,pitch_category=form.category.data)
        db.session.add(new_pitch)
        db.session.commit()
    pitch=Pitch.query.all()
    return render_template('pitched.html',form=form, pitch=pitch)

@main.route('/pick', methods=['GET', 'POST'])
def pickup():
    pickup = Pitch.query.filter_by(pitch_category="pick-up-lines").all()
    print(pickup)
    return render_template('pickup.html', pitch=pickup)
@main.route('/Interview', methods=['GET', 'POST'])
def interview():
    interview = Pitch.query.filter_by(pitch_category="interview").all()
    print(interview)
    return render_template('interview.html', pitch=interview)
@main.route('/Product', methods=['GET', 'POST'])
def product():
    product = Pitch.query.filter_by(pitch_category="product").all()
    print(product)
    return render_template('product.html', pitch=product)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():

        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST','GET'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        user_photo = PhotoProfile(pic_path = path,user = user)
        db.session.commit()
    return redirect(url_for('main.update_profile',uname=uname))



@main.route('/user/comment',methods=['GET','POST'])
def comment():
    form = form

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{%block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{url_for('static',filename='css/movie.css')}}">
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- Content block -->
{% block content %}

<div class="container">

  {% if current_user.is_authenticated%}
    <h1>Hello {{current_user.username}}</h1>
  {% else %}
    <h1>Hello {{title}}</h1>
  {%endif%}
    <form>
        <input type="text" name="pitch_query" placeholder="Search for a Pitch" class="form-control">
        <input type="submit"  value="Submit" class="btn btn-default">
    </form>
    
</div>

{% endblock%}

app/templates/interview.html
{% for pitch in pitch %}
{{pitch.pitch_content}}
{% endfor %}

app/templates/macros.html
{% macro displayPitches(my_pitches) %}
{% for pitch in my_pitches %}
<div class="col-md-12 pitches">

   <p>{{pitch.pitch_content}}</p>

   <a href="/pitched/comment/{{pitch.id}}" <p>comment</p></a>


{% endfor %}
{% endmacro %}

{% macro displayComments(my_comments) %}
{% for comment in my_comments %}

<h2>{{ comment.comment_content }}</h2>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Home </a>
            </div>

                <div class="Pitchlist">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    Pitchlist
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{{url_for('main.post')}}">Pitch</a>
    <a class="dropdown-item" href="{{url_for('main.pickup')}}">Pickup lines</a>
    <a class="dropdown-item" href="{{url_for('main.interview')}}">Interview pitch</a>
    <a class="dropdown-item" href="{{url_for('main.product')}}">product pitch</a>
  </div>
</div>

<ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.update_pic',uname=current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>
        </div>
    </div>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro%}
{% block content %}
<div class="container">


  <div class="card">
    <div class="card-body">
      {{ macro.displayPitches(pitch) }}
    </div>
  </div>


<div class="col-md-12">
          {{ wtf.quick_form(comment_form) }}
</div>

{{ macro.displayComments(comment) }}
</div>
{% endblock %}

app/templates/pickup.html
{% for pitch in pitch %}
{{pitch.pitch_content}}
{% endfor %}

app/templates/pitched.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- Styles block -->



<!-- Content block -->
{% block content %}
<div class="container">

  {{ wtf.quick_form(form) }}

  <div class="row">

        <h1>/pitch</h1>
        <hr>

        {% if pitch %}
            {{ macro.displayPitches(pitch) }}

        {% else%}
            <h3 class="text-center">There is no pitch </h3>
        {% endif %}

    </div>

</div>
{% endblock %}

app/templates/product.html
{% for pitch in pitch %}
{{pitch.pitch_content}}
{% endfor %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
     {% if user.profile_pic_path %}

     <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

     {%else%}
     <p>No profile picture</p>

     {% endif %}

         {% if user == current_user %}

     <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

       <input type="file"  name="photo" class="form-control" required>
       <input type="submit">
     </form>
       {% endif %}
   </div>
</div>
{% for pitch in pitch %}
{{pitch.pitch_content}}
{% endfor %}

</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/review.html
{% extends 'base.html'%}

{% block content%}
<div class="container-fluid">


    <div class="col-sm-8">
      {{format_review|safe}}
    </div>
  </div>
</div>
{%endblock%}
<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="row">

      <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.pitch_title}}</a> </h2>
      </div>
    </div>

    {% endfor %}
{% endmacro %}

app/templates/search.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h3> Found {{ pitch| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayPitchList(pitch)}}
            </ul>

        </div>

    </div>
{% endblock %}